Repository harmonoid/harmonoid, pull requests merged in 2022-03, with the labels that each got.

#218 Yehuda main
  lib/core/playback.dart
  lib/utils/extensions.dart
  lib/youtube/youtube.dart
  lib/youtube/youtube_api.dart
  lib/youtube/youtube_tile.dart
Labels: bug, improvement, critical

#220 Yehuda main
  lib/core/playback.dart
  lib/interface/now_playing.dart
  lib/interface/now_playing_bar.dart
  lib/main.dart
Labels: bug, improvement

#221 Yehuda main
  lib/interface/collection/album.dart
  lib/interface/collection/artist.dart
  lib/interface/collection/playlist.dart
  lib/interface/now_playing.dart
  lib/interface/now_playing_bar.dart
Labels: enhancement

#237 fix bug #227
  Harmonoid_InnoSetup.iss
Labels: enhancement

#243 Update ru_RU.json
  assets/translations/ru_RU.json
Labels: enhancement
